---
- name: Restart service
  listen: Restart service
  become: true
  systemd:
    name: "{{ service_unit_name | default(service_id) }}"
    state: restarted
  delegate_to: "{{ container_ip | default(service_ip | default(inventory_hostname)) }}"

- name: Shred runtime secrets
  listen:
    - runtime secret cleanup
  ansible.builtin.include_tasks:
    file: secret_cleanup.yml
  loop: "{{ runtime_secret_cleanup_contexts | default([]) }}"
  loop_control:
    loop_var: cleanup_secret_context
  when: runtime_secret_cleanup_contexts is defined and runtime_secret_cleanup_contexts | length > 0

- name: Reset runtime secret cleanup queue
  listen:
    - runtime secret cleanup
  set_fact:
    runtime_secret_cleanup_contexts: []
  when: runtime_secret_cleanup_contexts is defined
