---
- name: Restart service
  listen: Restart service
  become: true
  systemd:
    name: "{{ service_unit_name | default(service_id) }}"
    state: restarted
  delegate_to: "{{ container_ip | default(service_ip | default(inventory_hostname)) }}"
