---
- name: Restart SSH service
  ansible.builtin.service:
    name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
    state: restarted

- name: Validate sudoers configuration
  ansible.builtin.command: visudo -cf /etc/sudoers
  changed_when: false

- name: Reload cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: true
  failed_when: false
