---
- name: Ensure apt prerequisites are present
  ansible.builtin.apt:
    name: "{{ docker_host_prereq_packages.get(ansible_distribution, docker_host_prereq_packages.get(ansible_os_family, [])) }}"
    state: present
    update_cache: true

- name: Create docker apt key directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Determine Docker repository architecture label
  ansible.builtin.set_fact:
    docker_host_arch: "{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}"

- name: Install Docker repository GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Configure Docker APT repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ docker_host_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache for Docker packages
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker engine components
  ansible.builtin.apt:
    name: "{{ docker_host_package_map.get(ansible_distribution, docker_host_package_map.get(ansible_os_family, [])) }}"
    state: present
