---
- name: Determine service unit name
  set_fact:
    effective_service_unit_name: "{{ service_unit_name | default(service_id) }}"

- name: Ensure service IP facts
  ansible.builtin.include_tasks:
    file: set_service_ip.yml

- name: Install service packages
  become: true
  apt:
    name: "{{ service_packages }}"
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: service_packages is defined and service_packages | length > 0

- name: Deploy service configuration files
  become: true
  copy:
    dest: "{{ item.path }}"
    mode: "{{ item.mode | default('0644') }}"
    content: "{{ item.content }}"
  loop: "{{ service_files | default([]) }}"
  notify: Restart service

- name: Copy systemd unit file
  become: true
  copy:
    src: "{{ runtime_config_path }}"
    dest: "/etc/systemd/system/{{ effective_service_unit_name }}.service"
    mode: '0644'
  notify: Restart service

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable service
  become: true
  systemd:
    name: "{{ effective_service_unit_name }}"
    enabled: yes

- name: Start service
  become: true
  systemd:
    name: "{{ effective_service_unit_name }}"
    state: started

- name: Run additional setup commands
  become: true
  command: "{{ item }}"
  loop: "{{ service_commands | default([]) }}"
  when: service_commands is defined and service_commands | length > 0
