---
- name: Normalise runtime secrets
  set_fact:
    runtime_secret_context: "{{ secrets | default({}) | normalize_secrets }}"

- name: Register runtime secret shredding handler
  set_fact:
    runtime_secret_cleanup_contexts: >-
      {{
        (runtime_secret_cleanup_contexts | default([]))
        + [
          cleanup_entry
        ]
      }}
  vars:
    cleanup_entry: >-
      {{
        {
          'env': runtime_secret_context.env,
          'files': runtime_secret_context.files,
          'shred': runtime_secret_context.shred_after_apply,
        }
        | combine(
          ((runtime_secret_env_path | default(none)) is not none)
          | ternary({'env_path': runtime_secret_env_path}, {})
        )
        | combine(
          ((runtime_secret_dir | default(none)) is not none)
          | ternary({'directory': runtime_secret_dir}, {})
        )
        | combine(runtime_secret_cleanup_entry_extra | default({}))
      }}
  when:
    - runtime_secret_context.env | length > 0 or runtime_secret_context.files | length > 0
  notify: runtime secret cleanup
  changed_when: true

- name: Ensure runtime secret directory exists
  file:
    path: "{{ runtime_secret_dir }}"
    state: directory
    mode: "{{ runtime_secret_dir_mode | default('0700') }}"
  when:
    - runtime_secret_dir is not none
    - runtime_secret_context.files | length > 0
  become: {{ runtime_secret_become | default(false) }}

- name: Write runtime secret files
  copy:
    dest: "{{ runtime_secret_dir }}/{{ item.name }}"
    mode: "{{ item.mode | default('0400') }}"
    content: "{{ item.content | default('') }}"
  loop: "{{ runtime_secret_context.files }}"
  when:
    - runtime_secret_dir is not none
    - runtime_secret_context.files | length > 0
  no_log: true
  become: {{ runtime_secret_become | default(false) }}

- name: Write runtime secret environment file
  copy:
    dest: "{{ runtime_secret_env_path }}"
    mode: "{{ runtime_secret_env_mode | default('0600') }}"
    content: |-
      {% for item in runtime_secret_context.env %}
      {{ item.name }}={{ item.value }}
      {% endfor %}
  when:
    - runtime_secret_write_env_file | default(false)
    - runtime_secret_env_path is not none
    - runtime_secret_context.env | length > 0
  no_log: true
  become: {{ runtime_secret_become | default(false) }}
