---
- name: Load LXC configuration
  set_fact:
    lxc_config: "{{ lookup('file', runtime_config_path) | from_yaml }}"

- name: Ensure container_ip is defined
  assert:
    that:
      - lxc_config.container_ip is defined
      - lxc_config.container_ip | length > 0
    fail_msg: "Rendered Proxmox configuration must define container_ip"

- name: Validate Proxmox API token configuration
  assert:
    that:
      - proxmox_api_token_id is defined
      - proxmox_api_token_id | length > 0
      - proxmox_api_token_secret is defined
      - proxmox_api_token_secret | length > 0
      - proxmox_api_host is defined
      - proxmox_api_host | length > 0
      - proxmox_node is defined
      - proxmox_node | length > 0
    fail_msg: "Proxmox API token credentials (id/secret) and target node must be defined"

- name: Set container IP facts
  set_fact:
    container_ip: "{{ lxc_config.container_ip }}"
    service_ip: "{{ lxc_config.container_ip }}"

- name: Create LXC container
  community.general.proxmox:
    vmid: "{{ lxc_config.container.vmid }}"
    hostname: "{{ lxc_config.container.hostname }}"
    node: "{{ proxmox_node }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ proxmox_api_host }}"
    ostemplate: "{{ lxc_config.container.ostemplate }}"
    disk: "{{ lxc_config.container.disk }}"
    cores: "{{ lxc_config.container.cores }}"
    memory: "{{ lxc_config.container.memory }}"
    swap: "{{ lxc_config.container.swap }}"
    netif: "{{ lxc_config.container.netif }}"
    onboot: "{{ lxc_config.container.onboot }}"
    unprivileged: "{{ lxc_config.container.unprivileged }}"
    features: "{{ lxc_config.container.features | default(omit, true) }}"
    state: present

- name: Start container
  community.general.proxmox:
    vmid: "{{ lxc_config.container.vmid }}"
    node: "{{ proxmox_node }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_host: "{{ proxmox_api_host }}"
    state: started

- name: Wait for container SSH
  wait_for:
    host: "{{ container_ip }}"
    port: 22
    timeout: 120

- name: Install packages in container
  delegate_to: "{{ container_ip }}"
  become: true
  apt:
    name: "{{ lxc_config.setup.packages | default([]) }}"
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: lxc_config.setup.packages is defined and lxc_config.setup.packages | length > 0

- name: Write config files
  delegate_to: "{{ container_ip }}"
  become: true
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.path }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ lxc_config.setup.config | default([]) }}"

- name: Enable and start services
  delegate_to: "{{ container_ip }}"
  become: true
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(true) }}"
    state: "{{ item.state | default('started') }}"
    daemon_reload: true
  loop: "{{ lxc_config.setup.services | default([]) }}"

- name: Run additional setup commands
  delegate_to: "{{ container_ip }}"
  become: true
  command: "{{ item }}"
  loop: "{{ lxc_config.setup.commands | default([]) }}"
  when: lxc_config.setup.commands is defined and lxc_config.setup.commands | length > 0
