---
- name: Remove secret environment file after apply
  ansible.builtin.file:
    path: "{{ cleanup_secret_env_path }}"
    state: absent
  when:
    - cleanup_secret_shred | default(true) | bool
    - cleanup_secret_env | default([]) | length > 0
  become: "{{ cleanup_become | default(false) }}"
  no_log: "{{ cleanup_env_no_log | default(false) }}"

- name: Remove secret files after apply
  ansible.builtin.file:
    path: "{{ cleanup_secret_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ cleanup_secret_files | default([]) }}"
  when:
    - cleanup_secret_shred | default(true) | bool
    - cleanup_secret_files | default([]) | length > 0
  no_log: true
  become: "{{ cleanup_become | default(false) }}"

- name: Remove secret directory after apply
  ansible.builtin.file:
    path: "{{ cleanup_secret_dir }}"
    state: absent
  when:
    - cleanup_secret_shred | default(true) | bool
    - cleanup_secret_files | default([]) | length > 0
  become: "{{ cleanup_become | default(false) }}"
