---
- name: Include package hardening tasks
  ansible.builtin.import_tasks: packages.yml

- name: Include cockpit hardening tasks
  ansible.builtin.import_tasks: cockpit.yml

- name: Include account hardening tasks
  ansible.builtin.import_tasks: accounts.yml

- name: Include sysctl hardening tasks
  ansible.builtin.import_tasks: sysctl.yml

- name: Include SSH hardening tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Include sudo hardening tasks
  ansible.builtin.import_tasks: sudo.yml

- name: Include integrity monitoring tasks
  ansible.builtin.import_tasks: integrity.yml

- name: Include security tooling maintenance tasks
  ansible.builtin.import_tasks: security_tools.yml

- name: Include service hardening tasks
  ansible.builtin.import_tasks: services.yml
