---
- name: Resolve package set for distribution
  ansible.builtin.set_fact:
    hardening_package_target: "{{ hardening_packages_common.get(ansible_distribution, hardening_packages_common.get(ansible_os_family, [])) }}"

- name: Extend package set for Cockpit when enabled
  ansible.builtin.set_fact:
    hardening_package_target: "{{ (hardening_package_target + cockpit_packages) | unique }}"
  vars:
    cockpit_packages: "{{ hardening_cockpit_packages_map.get(ansible_distribution, hardening_cockpit_packages_map.get(ansible_os_family, [])) }}"
  when:
    - hardening_enable_cockpit | bool
    - cockpit_packages | length > 0

- name: Ensure base hardening packages are installed
  ansible.builtin.package:
    name: "{{ hardening_package_target }}"
    state: present
  when: hardening_package_target | length > 0

- name: Check for existing AIDE database
  ansible.builtin.stat:
    path: "{{ hardening_aide_db_path }}"
  register: hardening_aide_db

- name: Lock root password login
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Apply kernel and network sysctl hardening
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    reload: true
  loop: "{{ hardening_sysctl_common }}"

- name: Disable IPv6 when requested
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    reload: true
  loop: "{{ hardening_ipv6_disable_targets }}"
  when: not hardening_enable_ipv6

- name: Configure SSH daemon hardening drop-in
  ansible.builtin.template:
    src: ssh_hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/hardening.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart SSH service

- name: Ensure privileged separation directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /run/sshd
    - /var/run/sshd
    - /var/empty/sshd

- name: Configure sudoers timeout policy
  ansible.builtin.copy:
    dest: /etc/sudoers.d/timeout
    content: |-
      Defaults timestamp_timeout=5
    owner: root
    group: root
    mode: '0440'
  notify: Validate sudoers configuration

- name: Require TTY for sudo invocations
  ansible.builtin.copy:
    dest: /etc/sudoers.d/requiretty
    content: |-
      Defaults requiretty
    owner: root
    group: root
    mode: '0440'
  notify: Validate sudoers configuration

- name: Deploy SSH authorized keys when provided
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    manage_dir: true
  loop: "{{ hardening_authorized_users }}"
  when: hardening_authorized_users | length > 0

- name: Enforce secure umask defaults
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: 'umask 027'
    insertafter: EOF
    state: present
  loop: "{{ hardening_umask_targets }}"
  ignore_errors: true

- name: Ensure weekly AIDE integrity check cron job exists
  ansible.builtin.cron:
    name: Weekly AIDE check
    minute: "{{ hardening_weekly_aide_check_minute }}"
    hour: "{{ hardening_weekly_aide_check_hour }}"
    weekday: "{{ hardening_weekly_aide_check_day }}"
    user: root
    job: /usr/bin/aide --check
    state: present

- name: Disable unnecessary services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ (hardening_disable_services + hardening_additional_disable_services) | unique }}"
  ignore_errors: true

- name: Ensure Cockpit socket is disabled when Cockpit is not enabled
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: false
    state: stopped
    daemon_reload: true
  when: not hardening_enable_cockpit
  failed_when: false
  ignore_errors: true

- name: Remove Cockpit socket overrides when Cockpit is disabled
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d
    state: absent
  when: not hardening_enable_cockpit

- name: Ensure Cockpit socket override directory exists when enabled
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d
    state: directory
    mode: '0755'
  when: hardening_enable_cockpit

- name: Configure Cockpit bind address override
  ansible.builtin.copy:
    dest: /etc/systemd/system/cockpit.socket.d/listen.conf
    mode: '0644'
    content: |-
      [Socket]
      ListenStream=
      ListenStream={{ hardening_cockpit_bind_address }}:9090
  when: hardening_enable_cockpit
  notify: Reload cockpit socket
