---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages to latest available
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true

- name: Ensure unattended upgrades configuration is present
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |-
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    owner: root
    group: root
    mode: '0644'

- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Configure ufw default policies
  ansible.builtin.command: "{{ item }}"
  args:
    warn: false
  loop:
    - ufw default deny incoming
    - ufw default allow outgoing
  changed_when: false

- name: Allow SSH in ufw
  ansible.builtin.command: "ufw allow {{ hardening_ssh_port }}/tcp"
  args:
    warn: false
  changed_when: false

- name: Allow published service ports in ufw
  ansible.builtin.command: "ufw allow {{ item }}"
  args:
    warn: false
  loop: "{{ system_hardening_allowed_ports }}"
  changed_when: false
  when: system_hardening_allowed_ports | length > 0

- name: Allow cockpit management access in ufw
  ansible.builtin.command: "ufw allow from {{ item }} to any port 9090 proto tcp"
  args:
    warn: false
  loop: "{{ hardening_cockpit_allowed_sources }}"
  changed_when: false
  when:
    - hardening_enable_cockpit
    - hardening_cockpit_allowed_sources | length > 0

- name: Enable ufw firewall
  ansible.builtin.command: ufw --force enable
  args:
    warn: false
  changed_when: false

- name: Deploy fail2ban SSH jail configuration
  ansible.builtin.template:
    src: fail2ban_ssh.conf.j2
    dest: /etc/fail2ban/jail.d/ssh.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable security related services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - unattended-upgrades
    - fail2ban
    - auditd
    - acct
    - clamav-freshclam
    - clamav-daemon

- name: Update rkhunter databases
  ansible.builtin.command: "{{ item }}"
  changed_when: false
  failed_when: false
  loop:
    - rkhunter --propupd
    - rkhunter --update
  when: ansible_facts.packages.get('rkhunter') is defined

- name: Initialize AIDE database on Debian-based hosts
  ansible.builtin.command: aideinit
  async: "{{ hardening_aide_init_timeout if hardening_use_async_aide else omit }}"
  poll: "{{ 0 if hardening_use_async_aide else omit }}"
  register: aide_init_debian_start
  when:
    - ansible_facts.packages.get('aide') is defined
    - not hardening_aide_db.stat.exists

- name: Wait for AIDE initialization to finish on Debian hosts
  ansible.builtin.async_status:
    jid: "{{ aide_init_debian_start.ansible_job_id }}"
  register: aide_init_debian_result
  until: aide_init_debian_result.finished
  retries: "{{ hardening_aide_async_retries | int }}"
  delay: "{{ hardening_aide_async_poll_interval | int }}"
  when:
    - ansible_facts.packages.get('aide') is defined
    - not hardening_aide_db.stat.exists
    - hardening_use_async_aide
    - aide_init_debian_start.ansible_job_id is defined
  failed_when: >-
    aide_init_debian_result.finished and (aide_init_debian_result.rc | default(0)) != 0
  changed_when: >-
    aide_init_debian_result.finished and (aide_init_debian_result.rc | default(0)) == 0

- name: Capture synchronous AIDE initialization result on Debian hosts
  ansible.builtin.set_fact:
    aide_init_debian: "{{ aide_init_debian_start }}"
  when:
    - ansible_facts.packages.get('aide') is defined
    - aide_init_debian_start is defined
    - (not hardening_use_async_aide) or (aide_init_debian_start.ansible_job_id is not defined)

- name: Capture asynchronous AIDE initialization result on Debian hosts
  ansible.builtin.set_fact:
    aide_init_debian: "{{ aide_init_debian_result }}"
  when:
    - ansible_facts.packages.get('aide') is defined
    - hardening_use_async_aide
    - aide_init_debian_result is defined
    - aide_init_debian_start.ansible_job_id is defined

- name: Record AIDE database initialization on Debian hosts
  ansible.builtin.set_fact:
    hardening_aide_db:
      stat:
        exists: true
  when:
    - ansible_facts.packages.get('aide') is defined
    - aide_init_debian is defined
    - (aide_init_debian.rc | default(0)) == 0

