---
- name: Apply kernel and network sysctl hardening
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    reload: true
  loop: "{{ hardening_sysctl_common }}"

- name: Disable IPv6 when requested
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    reload: true
  loop: "{{ hardening_ipv6_disable_targets }}"
  when: not hardening_enable_ipv6
