---
kubernetes_version: "1.29"
kubernetes_cni_packages:
  - containerd
kubernetes_control_plane: false
kubernetes_sysctl_settings:
  - name: net.bridge.bridge-nf-call-iptables
    value: "1"
  - name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
  - name: net.ipv4.ip_forward
    value: "1"
