---
$schema: "https://json-schema.org/draft/2020-12/schema"
title: Ingress Intent
description: Canonical ingress declaration for application services.
type: object
additionalProperties: false
properties:
  enabled:
    type: boolean
    default: true
  routes:
    type: array
    minItems: 1
    items:
      type: object
      required:
        - host
        - port
      additionalProperties: true
      properties:
        host:
          type: string
          minLength: 1
        port:
          type: integer
          minimum: 1
          maximum: 65535
        path_prefix:
          type: string
          default: "/"
        websocket:
          type: boolean
          default: false
        sticky:
          type: string
          enum: [none, ip, cookie]
          default: none
        health:
          type: object
          additionalProperties: false
          properties:
            path:
              type: string
              default: "/"
            interval:
              type: string
              default: "30s"
            timeout:
              type: string
              default: "5s"
            method:
              type: string
            expected_status:
              oneOf:
                - type: integer
                - type: array
                  items:
                    type: integer
        tls:
          type: object
          additionalProperties: false
          properties:
            mode:
              type: string
              enum: [auto, provided, passthrough]
              default: auto
            hsts:
              type: boolean
              default: true
            alpn:
              type: array
              items:
                type: string
              default:
                - h2
                - http/1.1
            redirect_http_to_https:
              type: boolean
              default: true
            acme:
              type: object
              additionalProperties: false
              properties:
                challenge:
                  type: string
                  enum: [http, dns]
                  default: dns
                dns_provider:
                  type: string
                email:
                  type: string
                wildcard:
                  type: boolean
                  default: false
                eab_kid:
                  type: string
                eab_hmac_key:
                  type: string
            certificate_secret:
              type: string
            key_secret:
              type: string
            chain_secret:
              type: string
        headers:
          type: object
          additionalProperties: false
          properties:
            set:
              type: array
              items:
                type: string
              default: []
            remove:
              type: array
              items:
                type: string
              default: []
        rate_limit:
          type: object
          additionalProperties: false
          properties:
            requests_per_minute:
              type: integer
              minimum: 1
            burst:
              type: integer
              minimum: 1
        basic_auth:
          type: object
          additionalProperties: false
          properties:
            secret:
              type: string
            users:
              type: array
              items:
                type: string
        mtls:
          type: object
          additionalProperties: false
          properties:
            ca_secret:
              type: string
            required:
              type: boolean
              default: true
        allow_http:
          type: boolean
          default: false
required:
  - routes
