---
- name: Ensure OPNsense API credentials are provided for Caddy
  ansible.builtin.assert:
    that:
      - opnsense_caddy_api_key | length > 0
      - opnsense_caddy_api_secret | length > 0
    fail_msg: "opnsense_caddy_api_key and opnsense_caddy_api_secret must be provided to configure OPNsense Caddy"

- name: Enforce scoped OPNsense Caddy API key permissions
  ansible.builtin.assert:
    that:
      - "'root' not in (opnsense_caddy_api_key | lower)"
      - "'global' not in (opnsense_caddy_api_key | lower)"
    fail_msg: "opnsense_caddy_api_key must target the Caddy subsystem instead of root/global access"

- name: Build Caddy configuration payload
  ansible.builtin.set_fact:
    opnsense_caddy_configuration: "{{ edge_ingress_backends | default([]) | opnsense_caddy_configuration(bind_definitions) }}"
  vars:
    bind_definitions: "{{ opnsense_ingress_bind_addresses | default([{'address': '0.0.0.0', 'port': 80, 'tls': false}, {'address': '0.0.0.0', 'port': 443, 'tls': true}]) }}"

- name: Push Caddy configuration to OPNsense
  ansible.builtin.uri:
    url: "{{ opnsense_caddy_api_scheme }}://{{ opnsense_caddy_api_host }}:{{ opnsense_caddy_api_port }}/api/caddy/service/bulkImport"
    method: POST
    user: "{{ opnsense_caddy_api_key }}"
    password: "{{ opnsense_caddy_api_secret }}"
    force_basic_auth: true
    validate_certs: "{{ opnsense_caddy_api_verify_ssl }}"
    body_format: json
    status_code: 200
    body:
      configuration: {{ opnsense_caddy_configuration }}
  register: opnsense_caddy_import
  no_log: true

- name: Apply Caddy configuration on OPNsense
  when: opnsense_caddy_apply_changes | bool
  ansible.builtin.uri:
    url: "{{ opnsense_caddy_api_scheme }}://{{ opnsense_caddy_api_host }}:{{ opnsense_caddy_api_port }}/api/caddy/service/reconfigure"
    method: POST
    user: "{{ opnsense_caddy_api_key }}"
    password: "{{ opnsense_caddy_api_secret }}"
    force_basic_auth: true
    validate_certs: "{{ opnsense_caddy_api_verify_ssl }}"
    status_code: 200
    body_format: json
    body: {}
  no_log: true
