---
opnsense_api_scheme: https
opnsense_api_host: "{{ inventory_hostname }}"
opnsense_api_port: 443
opnsense_api_key: ""
opnsense_api_secret: ""
opnsense_api_verify_ssl: true
opnsense_apply_changes: true
opnsense_ingress_bind_addresses:
  - address: 0.0.0.0
    port: 80
    tls: false
  - address: 0.0.0.0
    port: 443
    tls: true
opnsense_tls_certificate_id: null
